data:
  dataflg: fltano120
  grid_res: 2
  input_path:
  - /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/data/processed/fltano120/olr.fltano120.noaa.2x2.1979to2022based1979to2001.nc
  input_vars:
  - olr
  lat_range: 20
  lead: 35
  memory_last: 0
  target_path: /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/data/target/noaa/ROMI_NOAA_1979to2022.nc
  target_vars:
  - ROMI
  test_end: '2021-12-31'
  test_start: '2010-01-01'
  train_end: '2009-12-31'
  train_start: '1979-05-01'
  transform: null
  val_end: '2015-12-31'
  val_start: '2010-01-01'
dataset_type: map_sym
exp_num: '91'
hidden_layers_str: '1024'
kernel_size_str: '11_83'
model:
  cnn:
    batch_norm: false
    channels_list:
    - 8
    - 128
    channels_list_str: '8_128'
    dropout: 0.1
    input_channel_num: 1
    input_map_size: 3780
    kernel_size:
    - 11
    - 83
    layer_num: 2
    name: CNN
    nlat: 21
    nlon: 180
    num_filters_enc: null
    padding: same
    stride: 1
  mlp:
    dropout: 0.4874921815781246
    hidden_layers:
    - 1024
    layer_num: 1
    output_size: 72
  name: CNN_MLP
model_save_path: /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/modelcheckpoints/map_sym/CNN_MLP/exp91/OLR_20deg_lead35_lr0.00018196018333262756_batch32_dropout0.4874921815781246_ch_8_128_ksize_11_83_hidden_1024_opt_SGD_mom0.9_wd1.3799703933628626e-05_mem0.pth
prediction_save_path: /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/predictions/map_sym/CNN_MLP/exp91/OLR_20deg_lead35_lr0.00018196018333262756_batch32_dropout0.4874921815781246_ch_8_128_ksize_11_83_hidden_1024_opt_SGD_mom0.9_wd1.3799703933628626e-05_mem0.nc
pretrained_path: null
training:
  batch_size: 32
  criterion: MSELoss
  early_stopping_patience: 10
  epochs: 100
  learning_rate: 0.00018196018333262756
  momentum: 0.9
  optimizer: SGD
  scheduler:
    T_max: 100
    type: CosineAnnealingLR
  weight_decay: 1.3799703933628626e-05
