data:
  dataflg: gravity
  grid_res: 2
  input_path:
  - /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/data/processed/filtered/olrnoaa.gravity.T2to3.nc
  input_vars:
  - olr
  lat_range: 10
  lead: 35
  memory_last: 95
  target_path: /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/data/target/noaa/ROMI_NOAA_1979to2022.nc
  target_vars:
  - ROMI
  test_end: '2021-12-31'
  test_start: '2010-01-01'
  train_end: '2009-12-31'
  train_start: '1979-05-01'
  transform: null
  val_end: '2015-12-31'
  val_start: '2010-01-01'
dataset_type: hov
exp_num: '5'
hidden_layers_str: '1024_1024'
kernel_size_str: '1_9'
model:
  cnn:
    batch_norm: false
    channels_list:
    - 4
    - 64
    channels_list_str: '4_64'
    dropout: 0.1
    input_channel_num: 1
    input_map_size: 17280
    kernel_size:
    - 1
    - 9
    layer_num: 2
    name: CNN
    nlon: 180
    num_filters_enc: null
    padding: same
    stride: 1
  mlp:
    dropout: 0.4356618276961871
    hidden_layers:
    - 1024
    - 1024
    layer_num: 2
    output_size: 72
  name: CNN_MLP
model_save_path: /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/modelcheckpoints/hov/CNN_MLP/exp5/OLR_10deg_lead35_lr3.010582377447385e-05_batch8_dropout0.4356618276961871_ch_4_64_ksize_1_9_hidden_1024_1024_opt_SGD_mom0.9_wd3.3721845038466615e-05_mem95.pth
prediction_save_path: /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/predictions/hov/CNN_MLP/exp5/OLR_10deg_lead35_lr3.010582377447385e-05_batch8_dropout0.4356618276961871_ch_4_64_ksize_1_9_hidden_1024_1024_opt_SGD_mom0.9_wd3.3721845038466615e-05_mem95.nc
pretrained_path: null
training:
  batch_size: 8
  criterion: MSELoss
  early_stopping_patience: 10
  epochs: 100
  learning_rate: 3.010582377447385e-05
  momentum: 0.9
  optimizer: SGD
  scheduler:
    T_max: 100
    type: CosineAnnealingLR
  weight_decay: 3.3721845038466615e-05
