# dataset_type: "hov_two"
dataset_type: "hov_two_allleads"

model:
  name: "UNet_A"
  cnn:
    name: "CNN"  # Name of the model
    input_channel_num: 2  # Number of input channels (e.g., RGB images have 3 channels)
    channels_list: [32,8]  # Number of channels in the first hidden layer
    # kernel_size: 3  # Size of the convolutional kernel
    kernel_size: "3"  # Size of the convolutional kernel
    stride: 1  # Stride for the convolution
    padding: "same"  # Padding type ('same' or integer)
    dropout: 0.1  # Dropout rate for regularization
    batch_norm: false  # Whether to use batch normalization
    nlon: 144  # the size of input map nlon
  mlp:
    hidden_layers: [1024, 128]
    output_size: 62
    dropout: 0.3

# training:
#   batch_size: 32
#   epochs: 20
#   optimizer: "Adam"
#   criterion: "MSELoss"
#   learning_rate: 0.0005
#   scheduler:
#     type: "CosineAnnealingLR"

training:
  batch_size: 32
  epochs: 20
  optimizer: "SGD"
  criterion: "MSELoss"
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.001
  scheduler:
    type: "CosineAnnealingLR"

data:
  # input_path: /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/data/raw/olr.day.mean.nc
  input_path: /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/data/raw/olr.day.mean.nc
  target_path: /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/data/target/romi/ROMI_NOAA_1979to2022.nc
  input_vars: ['olr']
  target_vars: ['ROMI']
  # train_start: '2014-01-01'
  train_start: '1979-01-01'
  train_end: '2009-12-31'
  val_start: '2010-01-01'
  val_end: '2015-12-31'
  test_start: '2020-01-01'
  test_end: '2022-12-31'
  lead: 25
  lat_range: 15
  transform: null
  # memory_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]
  # memory_list: [0, 1, 2, 3, 4]
  memory_last: 29

exp_num: 1

channels_list_str: "32_8_2"
hidden_layers_str: "2048_256"

pretrained_path: null 
model_save_path: "/pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/modelcheckpoints/hov2/{model_name}/exp{exp_num}/OLR_{lat_range}deg_lead{lead}_lr{lr}_batch{batch_size}_dropout{dropout}_ch_{channels_list_str}_ksize_{kernel_size}_hidden_{hidden_layers_str}_opt_{optimizer}_mom{momentum}_wd{weight_decay}_mem{memory_last}.pth"
prediction_save_path: "/pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/predictions/hov2/{model_name}/exp{exp_num}/OLR_{lat_range}deg_lead{lead}_lr{lr}_batch{batch_size}_dropout{dropout}_ch_{channels_list_str}_ksize_{kernel_size}_hidden_{hidden_layers_str}_opt_{optimizer}_mom{momentum}_wd{weight_decay}_mem{memory_last}.nc"
