data:
  dataflg: raw
  grid_res: 2
  input_path:
  - /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/data/raw/olr.day.noaa.2x2.nc
  input_vars:
  - olr
  lat_range: 10
  lead: 35
  memory_last: 0
  residual: false
  target_path: /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/data/target/noaa/ROMI_NOAA_1979to2022.nc
  target_vars:
  - ROMI
  test_end: '2021-12-31'
  test_start: '2010-01-01'
  train_end: '2009-12-31'
  train_start: '1979-05-01'
  transform: null
  val_end: '2015-12-31'
  val_start: '2010-01-01'
  window_len: 11
dataset_type: latavg
exp_num: '5'
hidden_layers_str: '512_256'
kernel_size_str: '1_123'
model:
  cnn:
    batch_norm: false
    channels_list:
    - 4
    - 4
    channels_list_str: '4_4'
    dropout: 0.1
    input_channel_num: 1
    input_map_size: 180
    kernel_size:
    - 1
    - 123
    layer_num: 2
    name: CNN
    nlat: 1
    nlon: 180
    num_filters_enc: null
    padding: same
    stride: 1
  mlp:
    dropout: 0.41458547219033803
    hidden_layers:
    - 512
    - 256
    layer_num: 2
    output_size: 72
  name: CNN_MLP
model_save_path: /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/modelcheckpoints/latavg/CNN_MLP/exp5/OLR_10deg_lead35_lr1.6917872833929117e-05_batch64_dropout0.41458547219033803_ch_4_4_ksize_1_123_hidden_512_256_opt_Adam_mom0.9_wd0.0001129374849595889_mem0.pth
prediction_save_path: /pscratch/sd/l/linyaoly/MJO_ML_2025/script/model/predictions/latavg/CNN_MLP/exp5/OLR_10deg_lead35_lr1.6917872833929117e-05_batch64_dropout0.41458547219033803_ch_4_4_ksize_1_123_hidden_512_256_opt_Adam_mom0.9_wd0.0001129374849595889_mem0.nc
pretrained_path: null
training:
  batch_size: 64
  criterion: MSELoss
  early_stopping_patience: 10
  epochs: 100
  learning_rate: 1.6917872833929117e-05
  momentum: 0.9
  optimizer: Adam
  scheduler:
    T_max: 100
    type: CosineAnnealingLR
  weight_decay: 0.0001129374849595889
